"""
高影響イベントの初期定義表。
impact/category はここで固定値として与える（毎回自動判定はしない）。
"""

EVENT_DEFINITIONS = {
    "us_fomc": {
        "name": "FOMC 政策金利発表・議長会見",
        "name_en": "FOMC Meeting",
        "country": "US",
        "category": "central_bank",
        "impact": "high",
        "is_template": False,
        "source_url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    },
    "us_cpi": {
        "name": "消費者物価指数 CPI（前年比）",
        "name_en": "Consumer Price Index",
        "country": "US",
        "category": "cpi",
        "impact": "high",
        "is_template": True,
        "source_url": "https://www.bls.gov/schedule/news_release/cpi.htm",
    },
    "us_nfp": {
        "name": "非農業部門雇用者数 NFP",
        "name_en": "Employment Situation",
        "country": "US",
        "category": "employment",
        "impact": "high",
        "is_template": True,
        "source_url": "https://www.bls.gov/schedule/news_release/empsit.htm",
    },
    "us_pce": {
        "name": "PCEデフレーター",
        "name_en": "Personal Income and Outlays",
        "country": "US",
        "category": "other",
        "impact": "high",
        "is_template": True,
        "source_url": "https://apps.bea.gov/API/signup/release_dates.json",
    },
    "us_gdp": {
        "name": "GDP速報",
        "name_en": "Gross Domestic Product",
        "country": "US",
        "category": "gdp",
        "impact": "high",
        "is_template": True,
        "source_url": "https://apps.bea.gov/API/signup/release_dates.json",
    },
    "us_ism_mfg": {
        "name": "ISM製造業景況指数",
        "name_en": "ISM Manufacturing PMI",
        "country": "US",
        "category": "sentiment",
        "impact": "mid",
        "is_template": True,
        "source_url": "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-pmi-reports/",
    },
    "us_ism_nonmfg": {
        "name": "ISM非製造業景況指数",
        "name_en": "ISM Non-Manufacturing PMI",
        "country": "US",
        "category": "sentiment",
        "impact": "mid",
        "is_template": True,
        "source_url": "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-pmi-reports/",
    },
    "jp_boj_meeting": {
        "name": "日銀金融政策決定会合",
        "name_en": "BOJ Monetary Policy Meeting",
        "country": "JP",
        "category": "central_bank",
        "impact": "high",
        "is_template": False,
        "source_url": "https://www.boj.or.jp/mopo/mpmsche_minu/index.htm",
    },
    "jp_tankan": {
        "name": "日銀短観 大企業製造業DI",
        "name_en": "BOJ Tankan",
        "country": "JP",
        "category": "sentiment",
        "impact": "high",
        "is_template": True,
        "source_url": "https://www.boj.or.jp/statistics/outline/tkohyos.xlsx",
    },
    "jp_cpi": {
        "name": "全国CPI（コア・前年比）",
        "name_en": "Japan CPI (National)",
        "country": "JP",
        "category": "cpi",
        "impact": "mid",
        "is_template": True,
        "source_url": "https://www.e-stat.go.jp/release-calendar",
    },
    "jp_gdp": {
        "name": "GDP速報",
        "name_en": "Japan GDP (QE)",
        "country": "JP",
        "category": "gdp",
        "impact": "high",
        "is_template": True,
        "source_url": "https://www.esri.cao.go.jp/jp/sna/kouhyou/kouhyou_top.html",
    },
}
